### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by NuLogicSystems**
Update look to match previous versions of firefox
add pref that sets the default state of all plugins to enabled.

### CODE REVIEW

**Comment by NuLogicSystems** [comment]
Please test, if this works under Debian.
If not, It could just be a difference in the way the extensions are packaged.
xul-ext-xxx (xpi unpacked) vs. packaging the xpi files themselves.

**Comment by llelectronics** [comment]
This UI changes what it looks like now. (did not test with ublock so far)
The current look with having one bar only (not a separate search bar) and new window, then download button then ublock origin is what is wanted. (Like discussed with Clemens on this weeks sprint)

**Comment by NuLogicSystems** [comment]
OK, I did not know that, I do apologize.
I was going with what Firefox has always look like under netrunner, even the 17.10 release.
You can go ahead ignore this whole issue and pull request then.
I'll go ahead and remove my fork and just use what you have already done.

**Comment by NuLogicSystems** [comment]
So before I remove my fork, just to be sure, this would be correct then?
http://www.enlightenment.org/ss/e-5a2ac023d5e4d4.19254611.jpg

**Comment by llelectronics** [comment]
Yes this looks right.

**Comment by NuLogicSystems** [comment]
OK, I'm deleting my fork and closing this pull request then.
Sorry about all this. ;)

**Pull request closed without merging**
